### ISSUE TITLE
jetbrains code implementation related questions

### ISSUE THREAD

**Issue by jackyliu16** [NikSneMC/NikSOS#10]
Recently I have been studying the adaptation of ja-netfilter, I see [your code](https://github.com/NikSneMC/NikSOS/blob/a37dd1477521925fb646f0d3f26839d8378a8047/home/niksne/programs/editors/jetbrains.nix#L23), but I don't quite understand how you can make it run without defining the implementation through modules.

If it's all right with you, could you tell me how it works here?

**Comment by NikSneMC** [comment]
> Recently I have been studying the adaptation of ja-netfilter, I see [your code](https://github.com/NikSneMC/NikSOS/blob/a37dd1477521925fb646f0d3f26839d8378a8047/home/niksne/programs/editors/jetbrains.nix#L23), but I don't quite understand how you can make it run without defining the implementation through modules.
> 
> If it's all right with you, could you tell me how it works here?

I just override vmoptions for each IDE in list. ja-netfilter is packaged [here](https://github.com/NikSneMC/NikSOS/blob/a37dd1477521925fb646f0d3f26839d8378a8047/pkgs/ja-netfilter/default.nix)

**Comment by jackyliu16** [comment]
Actually, I'm curious about this.

programs.jetbrains-remote = {
  enable = true;
  inherit ides;
};

From my general understanding, it seems that this programs.jetbrains exists only if the corresponding modules are configured through HM or nixos and then imported, but I don't see the relevant part.

**Comment by NikSneMC** [comment]
> Actually, I'm curious about this.
> 
> programs.jetbrains-remote = { enable = true; inherit ides; };
> 
> From my general understanding, it seems that this programs.jetbrains exists only if the corresponding modules are configured through HM or nixos and then imported, but I don't see the relevant part.

https://home-manager-options.extranix.com/?release=master&query=jetbrains

**Comment by jackyliu16** [comment]
My fault, I have been using version 23.11 before and haven't changed my mind yet.

Thank you very much for your help. Finally, I wish you good health and all the best。
