### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dieBakterie** [NikSneMC/NikSOS#8]
![IMG_20240323_030329](https://github.com/NikSneMC/NikSOS/assets/50206827/79c32b40-8998-4b84-8e33-47ad205441cf)

**Comment by dieBakterie** [comment]
Syntax Errors in modules.nix and bootloader.nix

**Comment by NikSneMC** [comment]
there's a **lot** of errors in repo...

**Comment by NikSneMC** [comment]
I think there's no typos now
